# -*- coding: utf-8 -*-
"""
ROLTAR - strony szczegółowe (2. poziom serwisu).
Moduł ładowany przez build_site.py (exec w globalnej przestrzeni nazw)
tuż przed sekcją zapisu. Każda strona powstaje pod ORYGINALNĄ nazwą pliku
serwisu ROLTAR, więc po wgraniu pakietu nadpisuje starą podstronę
(np. ndr.htm, bs.htm, rolety1234.htm) i działa w nowej szacie.
"""


def _paras_to_html(paras):
    return "".join(f"<p>{p}</p>" for p in paras)


def det_page(fname, title, desc, active, crumb, h1, lead,
             img, alt, h2, paras, feats=None, model_extra=None,
             links_title="Powiązane strony", links=None):
    """Składa pełną stronę szczegółową: hero + zdjęcie/tekst + cechy + dodatki."""
    body = page_hero(crumb, h1, lead)
    body += (f'<section class="section"><div class="container">'
             f'{split(img, alt, h2, _paras_to_html(paras))}'
             f'</div></section>')
    if feats:
        lis = "".join(f'<li>{I["check"]}<span>{t}</span></li>' for t in feats)
        body += (f'<section class="section section-alt"><div class="container">'
                 f'<div class="section-head"><h2>Najważniejsze cechy</h2></div>'
                 f'<ul class="checklist">{lis}</ul></div></section>')
    if model_extra:
        body += model_extra
    if links:
        body += (f'<section class="section"><div class="container">'
                 f'{lbox(links_title, "powiązane strony", links)}</div></section>')
    return page(fname, title, desc, active, body)


def models_section(title, note, rows):
    """Sekcja z listą modeli (markizy itp.). rows = [(nazwa, etykieta, opis)]"""
    items = []
    for name, arch, desc in rows:
        a = f' <span class="arch">{arch}</span>' if arch else ""
        items.append(f'<div class="model-item"><h3>{name}{a}</h3><p>{desc}</p></div>')
    return (f'<section class="section section-alt"><div class="container">'
            f'<div class="section-head"><h2>{title}</h2>'
            f'{"<p>" + note + "</p>" if note else ""}</div>'
            f'{"".join(items)}</div></section>')


# ======================================================================
# ROLETY ZEWNĘTRZNE / SYSTEMY MONTAŻU
# ======================================================================

pages["rolaluminiowe.htm"] = det_page("rolaluminiowe.htm",
    "Rolety aluminiowe zewnętrzne - ROLTAR Tarnów",
    "Rolety zewnętrzne aluminiowe: zimą redukują straty ciepła, latem chronią przed nagrzewaniem, ograniczają hałas i zwiększają bezpieczeństwo. Produkcja i montaż.",
    "rolety.htm", "Rolety zewnętrzne", "Rolety aluminiowe",
    "Powszechnie stosowany system osłon okiennych, który spełnia wiele funkcji - od oszczędności energii po ochronę przed włamaniem.",
    "assets/rolety-zewnetrzne.jpg", "Rolety aluminiowe zewnętrzne na oknie",
    "Wielofunkcyjna osłona okienna",
    ["Zimą <strong>redukują straty ciepła</strong>, latem zabezpieczają wnętrze przed nagrzewaniem, chronią okna przed deszczem i śniegiem, ograniczają hałas dochodzący z zewnątrz i <strong>zwiększają bezpieczeństwo mieszkańców</strong>.",
     "Rolety wykonane są całkowicie z aluminium, dzięki czemu nie ulegają korozji i nie wymagają konserwacji. Różnorodność systemów pozwala zastosować je na każdym etapie powstawania budynku, a bogata kolorystyka umożliwia doskonałe dopasowanie do fasad i elewacji - zarówno istniejących, jak i nowo budowanych.",
     "Podnoszenie i opuszczanie rolet może odbywać się ręcznie lub za pomocą <strong>silników elektrycznych</strong> z zastosowaniem różnych systemów sterowania."],
    feats=["Materiał w 100% aluminiowy - odporny na korozję",
           "Zimą ogranicza straty ciepła przez okna",
           "Latem chroni wnętrze przed nagrzewaniem",
           "Tłumi hałas dochodzący z zewnątrz",
           "Zwiększa bezpieczeństwo przed włamaniem",
           "Sterowanie ręczne lub silnikiem elektrycznym"],
    links_title="Warianty montażu rolet zewnętrznych",
    links=[deep("systadap.htm", "System adaptacyjny", "do istniejących budynków - na ramy okienne lub mur"),
           deep("podtynk.htm", "System podtynkowy INTEGRO", "skrzynka roletowa zatynkowana w ścianie"),
           deep("nadpro.htm", "System nadprożowy RKS", "rolokaseta w nowo wznoszonych budynkach"),
           deep("rolety1234.htm", "System MONOBLOK", "gotowa kaseta do okien PCV, drewnianych i aluminiowych"),
           deep("ndr.htm", "Silniki i sterowania do rolet", "napędy, sterowanie radiowe i automatyczne"),
           deep("rolety.htm", "Rolety i żaluzje - oferta", "wszystkie systemy rolet w jednym miejscu")])

pages["systadap.htm"] = det_page("systadap.htm",
    "Rolety adaptacyjne - montaż na istniejące okna | ROLTAR Tarnów",
    "System adaptacyjny rolet zewnętrznych do istniejących budynków. Roleta montowana do ram okna lub po obrysie okna do muru, bez wymiany okien.",
    "rolety.htm", "Rolety zewnętrzne", "System adaptacyjny",
    "Rolety montowane bez wymiany okien - do istniejących budynków i mieszkań.",
    "assets/rolety-zewnetrzne.jpg", "Roleta adaptacyjna zamontowana na istniejącym oknie",
    "Dla istniejących budynków",
    ["System przeznaczony do stosowania w <strong>istniejących budynkach</strong> - również w mieszkaniach i domach, w których okna nie są wymieniane.",
     "Roleta może być zamocowana <strong>do ram okna</strong> lub <strong>po obrysie okna do muru</strong> - sposób montażu dobieramy do rodzaju okna i elewacji.",
     "Po zamontowaniu roleta działa jak fabryczna: można nią sterować ręcznie (taśma, korba) lub napędem elektrycznym z pilotem."],
    links_title="Zobacz również",
    links=[deep("rolaluminiowe.htm", "Rolety aluminiowe", "systemy i kolorystyka"),
           deep("podtynk.htm", "System podtynkowy INTEGRO", "skrzynka zatynkowana w ścianie"),
           deep("nadpro.htm", "System nadprożowy RKS", "rolokaseta w nowych budynkach"),
           deep("rolety1234.htm", "System MONOBLOK", "gotowa kaseta na okna"),
           deep("ndr.htm", "Silniki i sterowania do rolet", "automatyka do rolet")])

pages["podtynk.htm"] = det_page("podtynk.htm",
    "Rolety podtynkowe INTEGRO - ROLTAR Tarnów",
    "System podtynkowy INTEGRO: skrzynka roletowa zatynkowana w ścianie. Do budynków istniejących i nowo budowanych. Produkcja i montaż.",
    "rolety.htm", "Rolety zewnętrzne", "System podtynkowy INTEGRO",
    "Eleganckie rozwiązanie: kaseta roletowa znika w ścianie, widać tylko samą roletę.",
    "assets/rolety-zewnetrzne.jpg", "Roleta podtynkowa - kaseta ukryta w ścianie",
    "Kaseta zatynkowana w ścianie",
    ["System przeznaczony do stosowania w budynkach <strong>już istniejących i nowo budowanych</strong>.",
     "Umożliwia <strong>zatynkowanie skrzynki roletowej</strong> - po wykończeniu ściany widoczny pozostaje tylko profil prowadnic i pancerz rolety.",
     "To rozwiązanie doceniane w nowoczesnym budownictwie - roleta podtynkowa nie zaburza linii elewacji i dobrze współpracuje z ociepleniem budynku."],
    links_title="Zobacz również",
    links=[deep("systadap.htm", "System adaptacyjny", "montaż na istniejące okna"),
           deep("nadpro.htm", "System nadprożowy RKS", "rolokaseta w nadprożu"),
           deep("rolety1234.htm", "System MONOBLOK", "gotowa kaseta na okna"),
           deep("rolaluminiowe.htm", "Rolety aluminiowe", "funkcje i kolorystyka")])

pages["nadpro.htm"] = det_page("nadpro.htm",
    "Rolety nadprożowe RKS - ROLTAR Tarnów",
    "System nadprożowy RKS (rolokaseta) do nowo wznoszonych budynków, z zabudową od zewnątrz i wewnątrz. Dostępna roleta z siatką przeciw insektom.",
    "rolety.htm", "Rolety zewnętrzne", "System nadprożowy RKS",
    "Rolokaseta montowana w nadprożu okna - rozwiązanie dla nowo wznoszonych budynków.",
    "assets/rolety-zewnetrzne.jpg", "Rolokaseta w nadprożu okna",
    "Kaseta w nadprożu okna",
    ["System stosowany w <strong>nowo wznoszonych budynkach</strong>, przystosowany do całkowitej zabudowy z zewnątrz i wewnątrz budynku.",
     "Dzięki zabudowie kasety w nadprożu roleta nie wystaje przed elewację i nie zajmuje miejsca nad oknem.",
     "Dostępna jest również wersja <strong>rolety zintegrowanej z siatką przeciw insektom</strong> - dwa w jednym: osłona przeciwsłoneczna i moskitiera."],
    links_title="Zobacz również",
    links=[deep("systadap.htm", "System adaptacyjny", "do istniejących okien"),
           deep("podtynk.htm", "System podtynkowy INTEGRO", "kaseta zatynkowana w ścianie"),
           deep("rolety1234.htm", "System MONOBLOK", "gotowa kaseta na okna"),
           deep("rolaluminiowe.htm", "Rolety aluminiowe", "funkcje i kolorystyka")])

pages["rolety1234.htm"] = det_page("rolety1234.htm",
    "Rolety zewnętrzne - systemy montażu | ROLTAR Tarnów",
    "Systemy rolet zewnętrznych: MONOBLOK, adaptacyjny, podtynkowy INTEGRO i nadprożowy RKS. Dobierzemy system do Twojego okna i etapu budowy.",
    "rolety.htm", "Rolety zewnętrzne", "System MONOBLOK",
    "Gotowa kaseta roletowa - idealne rozwiązanie dla nowych i remontowanych budynków.",
    "assets/rolety-zewnetrzne.jpg", "Kaseta rolety zewnętrznej nad oknem",
    "Kaseta gotowa do montażu",
    ["System MONOBLOK to <strong>gotowa kaseta z roletą</strong>, montowana nad oknem - proste i szybkie rozwiązanie dla nowych oraz remontowanych budynków.",
     "Sprawdza się przy oknach <strong>PCV, aluminiowych i drewnianych</strong>. Szeroka gama prowadnic pozwala dopasować system do każdego typu okna.",
     "Mechanizmy sterujące: <strong>taśma, sznurek, korba, sprężyna lub silnik</strong>. Kaseta ma estetyczny, zamknięty wygląd i chroni roletę przed czynnikami atmosferycznymi."],
    feats=["Prosty i szybki montaż",
           "Do okien PCV, aluminiowych i drewnianych",
           "Szeroka gama prowadnic",
           "Sterowanie: taśma, sznurek, korba, sprężyna lub silnik",
           "Standardowe akcesoria do rolet zewnętrznych",
           "Estetyczny, zamknięty wygląd kasety"],
    links_title="Pozostałe systemy montażu",
    links=[deep("systadap.htm", "System adaptacyjny", "do istniejących budynków"),
           deep("podtynk.htm", "System podtynkowy INTEGRO", "skrzynka zatynkowana"),
           deep("nadpro.htm", "System nadprożowy RKS", "rolokaseta w nadprożu"),
           deep("brrol.htm", "Bramy rolowane", "pancerz z profili PA 77"),
           deep("rolaluminiowe.htm", "Rolety aluminiowe", "funkcje i kolorystyka")])

# ======================================================================
# ŻALUZJE FASADOWE I WEWNĘTRZNE
# ======================================================================

pages["zaluzjefasadowe.htm"] = det_page("zaluzjefasadowe.htm",
    "Żaluzje fasadowe - ROLTAR Tarnów",
    "Żaluzje fasadowe zatrzymujące od 60% do 90% promieni słonecznych. Sterowanie ręczne i elektryczne. Idealne do biur i budynków z dużymi przeszkleniami.",
    "syst.zac.htm", "Systemy osłon okiennych", "Żaluzje fasadowe",
    "Zewnętrzne żaluzje do dużych przeszkleń - skuteczna ochrona przed upałem w budynkach biurowych i mieszkalnych.",
    "assets/refleksole.jpg", "Żaluzje fasadowe na przeszklonej elewacji",
    "Kontrola słońca na elewacji",
    ["Żaluzje fasadowe <strong>minimalizują nagrzewanie pomieszczeń</strong>, co prowadzi do istotnego ograniczenia konieczności stosowania klimatyzacji.",
     "Zatrzymują od <strong>60% do 90% promieni słonecznych</strong>. Dla porównania: w naszej strefie klimatycznej okno o powierzchni 1,5 m&sup2; wychodzące na południowy zachód zachowuje się jak grzejnik o mocy 1000 W - żaluzja fasadowa niweluje ten efekt.",
     "Umożliwiają też sterowanie rozproszeniem światła w pomieszczeniu - szczególnie zalecane w budynkach o dużej powierzchni przeszkleń. Możliwość sterowania <strong>ręcznego i elektrycznego</strong>."],
    feats=["Zatrzymują 60-90% promieni słonecznych",
           "Redukują koszty klimatyzacji",
           "Sterowanie rozproszeniem światła w pomieszczeniu",
           "Sterowanie ręczne lub elektryczne",
           "Do dużych przeszkleń i elewacji",
           "Nowoczesny wygląd budynku"],
    links_title="Zobacz również",
    links=[deep("refleksole.htm", "Refleksole", "osłony przeciwsłoneczne z tkanin"),
           deep("rolaluminiowe.htm", "Rolety aluminiowe", "osłony zewnętrzne na okna"),
           deep("syst.zac.htm", "Systemy osłon okiennych", "pełna oferta osłon")])

pages["pionowe.htm"] = det_page("pionowe.htm",
    "Żaluzje pionowe VERTICALE - ROLTAR Tarnów",
    "Żaluzje pionowe VERTICALE do dużych okien i biur. Szerokości lamel 127 i 89 mm, montaż do sufitu, nadproża i skośnych sufitów. Materiały z atestami.",
    "rolety.htm", "Rolety i żaluzje", "Żaluzje pionowe VERTICALE",
    "Praktyczna zasłona okienna, która poradzi sobie nawet z bardzo dużymi przeszkleniami.",
    "assets/zaluzje-pionowe.jpg", "Żaluzje pionowe w jasnym wnętrzu",
    "Do dużych przeszkleń",
    ["Praktyczna zasłona okienna pozwala zasłonić nawet <strong>bardzo duże powierzchnie przeszklone</strong>. Doskonała regulacja dopływu światła odbywa się przez system obracania pasów materiałowych.",
     "Wszystkie materiały posiadają <strong>atest higieniczny</strong> (niektóre są niepalne) i są impregnowane - można je odkurzać, a niektóre prać.",
     "Duża możliwość montażu: do sufitu, do nadproża oraz do skośnych sufitów. Bogaty wybór materiałów pozwala dopasować przesłonę praktycznie do każdego wnętrza."],
    feats=["Wykonanie w dwóch szerokościach lamel: 127 mm i 89 mm",
           "Montaż do sufitu, nadproża i skośnych sufitów",
           "Materiały z atestami higienicznymi",
           "Niektóre materiały niepalne",
           "Możliwość prania wybranych tkanin",
           "Duży wybór kolorów i struktur"],
    links_title="Zobacz również",
    links=[deep("poziome.htm", "Żaluzje poziome", "listki 16 i 25 mm"),
           deep("drewniane.htm", "Żaluzje drewniane", "szerokości 25 i 50 mm"),
           deep("plisowane.htm", "Żaluzje plisowane", "do okien o nietypowych kształtach"),
           deep("track.htm", "Panel track - japońska ściana", "panele na wielotorowej szynie"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony wewnętrzne")])

pages["poziome.htm"] = det_page("poziome.htm",
    "Żaluzje poziome 16 i 25 mm - ROLTAR Tarnów",
    "Żaluzje poziome z aluminiowych listek o szerokości 16 lub 25 mm. Montaż na każdą szybę, mechanizm samohamowny. Sprzedaż i montaż w Tarnowie.",
    "rolety.htm", "Rolety i żaluzje", "Żaluzje poziome",
    "Klasyczne żaluzje z aluminiowych listek - proste, praktyczne i niedrogie.",
    "assets/zaluzje-poziome.jpg", "Żaluzje poziome z wąskich listek",
    "Klasyka w każdym oknie",
    ["Żaluzje poziome to <strong>jedna z najtańszych osłon okiennych</strong>, wykonana z aluminiowych listek o szerokości <strong>16 lub 25 mm</strong>.",
     "Montowane indywidualnie na każdej szybie okiennej. Mechanizm <strong>samohamowny</strong> pozwala zatrzymać żaluzję w dowolnej pozycji.",
     "Za pomocą listek precyzyjnie reguluje się ilość wpadającego światła, a kolorystykę można dopasować do ram okiennych i wnętrza."],
    feats=["Listki aluminiowe 16 mm lub 25 mm",
           "Montaż na każdą szybę osobno",
           "Mechanizm samohamowny",
           "Precyzyjna regulacja światła",
           "Bogata paleta kolorów listek",
           "Łatwe utrzymanie w czystości"],
    links_title="Zobacz również",
    links=[deep("pionowe.htm", "Żaluzje pionowe VERTICALE", "do dużych okien"),
           deep("drewniane.htm", "Żaluzje drewniane", "wersja ekskluzywna"),
           deep("plisowane.htm", "Żaluzje plisowane", "tkaniny składane"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony wewnętrzne")])

pages["drewniane.htm"] = det_page("drewniane.htm",
    "Żaluzje drewniane i drewnopodobne - ROLTAR Tarnów",
    "Ekskluzywne żaluzje drewniane poziome o szerokości listek 25 i 50 mm. Naturalny charakter i elegancja we wnętrzu. Produkcja na wymiar.",
    "rolety.htm", "Rolety i żaluzje", "Żaluzje drewniane",
    "Drewno we wnętrzu to elegancja - żaluzja drewniana jest też elementem dekoracyjnym.",
    "assets/zaluzje-drewniane.jpg", "Żaluzje drewniane w salonie",
    "Naturalna elegancja",
    ["Żaluzja pozioma drewniana to <strong>produkt ekskluzywny</strong>, stosowany we wnętrzach również jako element dekoracyjny dopełniający charakter pomieszczenia.",
     "Dostępne wersje z listek o szerokości <strong>25 mm i 50 mm</strong>, w naturalnych odcieniach drewna oraz w wersji drewnopodobnej.",
     "Doskonale sprawdzają się w salonach, sypialniach i gabinetach - wprowadzają ciepło i naturalny materiał do wnętrza."],
    feats=["Szerokości listek: 25 mm i 50 mm",
           "Naturalne drewno i wersje drewnopodobne",
           "Element dekoracyjny wnętrza",
           "Ciepły, naturalny wygląd",
           "Wykonanie na wymiar",
           "Trwałe wykończenie powierzchni"],
    links_title="Zobacz również",
    links=[deep("poziome.htm", "Żaluzje poziome", "listki aluminiowe 16 i 25 mm"),
           deep("pionowe.htm", "Żaluzje pionowe VERTICALE", "do dużych okien"),
           deep("plisowane.htm", "Żaluzje plisowane", "lekkie przesłony materiałowe"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony wewnętrzne")])

pages["plisowane.htm"] = det_page("plisowane.htm",
    "Żaluzje plisowane i rolety plisowane - ROLTAR Tarnów",
    "Plisy okienne: eleganckie przesłony materiałowe do okien o nietypowych kształtach - trójkąt, trapez, półokrąg. Różne kierunki podnoszenia.",
    "rolety.htm", "Rolety i żaluzje", "Żaluzje plisowane",
    "Lekkie, składane tkaniny - rozwiązanie również dla okien o nietypowych kształtach.",
    "assets/zaluzje-plisowane.jpg", "Plisowana osłona w oknie",
    "Tkanina, która dopasuje się do okna",
    ["Bardzo eleganckie przesłony materiałowe z możliwością różnorodnego podnoszenia i opuszczania na oknie: <strong>z góry na dół, z dołu do góry, ze środka na dół i ze środka do góry</strong>.",
     "To jedyny system osłonowy pozwalający zasłonić okno o nietypowym kształcie - <strong>trójkąt, trapez czy półokrąg</strong>.",
     "Bardzo duży wybór tkanin pozwala zaspokoić niemal każdy gust - od lekkich transparentnych po całkowicie zaciemniające."],
    feats=["Różne kierunki podnoszenia tkaniny",
           "Do okien o nietypowych kształtach",
           "Lekka i kompaktowa konstrukcja",
           "Duży wybór tkanin i kolorów",
           "Wersje transparentne i zaciemniające",
           "Wykonanie na wymiar"],
    links_title="Zobacz również",
    links=[deep("poziome.htm", "Żaluzje poziome", "listki 16 i 25 mm"),
           deep("pionowe.htm", "Żaluzje pionowe VERTICALE", "do dużych okien"),
           deep("impresja.htm", "System IMPRESJA (dzień/noc)", "rolety z tkaniny naprzemiennej"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony wewnętrzne")])

# ======================================================================
# ROLETY TEKSTYLNE
# ======================================================================

pages["wolnowiszace.htm"] = det_page("wolnowiszace.htm",
    "Rolety wolnowiszące - ROLTAR Tarnów",
    "Rolety materiałowe wolnowiszące montowane do sufitu lub nadproża. Sterowanie łańcuszkiem lub silnikiem z pilotem, wykończenie falbaną.",
    "rolety.htm", "Rolety tekstylne", "Rolety wolnowiszące",
    "Najprostsza roleta materiałowa - uniwersalna i ekonomiczna osłona okna.",
    "assets/rolety-wewnetrzne.jpg", "Roleta materiałowa w oknie",
    "Klasyka w każdym oknie",
    ["Najprostsza roleta materiałowa, montowana do <strong>sufitu lub nadproża</strong>, zasłaniająca cały otwór okienny.",
     "Podnoszona za pomocą <strong>łańcuszka koralikowego lub silnika z pilotem</strong>. Możliwość wykończenia tkaniny ozdobną falbaną.",
     "Szeroki wybór tkanin - od lekkich, przepuszczających światło, po całkowicie zaciemniające."],
    feats=["Montaż do sufitu lub nadproża",
           "Zasłania cały otwór okienny",
           "Sterowanie łańcuszkiem lub silnikiem",
           "Możliwość wykończenia falbaną",
           "Duży wybór tkanin",
           "Szybka realizacja na wymiar"],
    links_title="Rolety w kasetach i systemach",
    links=[deep("mini.htm", "System MINI", "bezinwazyjny montaż na skrzydłach okien"),
           deep("besta.htm", "System BESTA", "kaseta montowana na szybę"),
           deep("luiza.htm", "System LUIZA", "kaseta z prowadnicami przestrzennymi"),
           deep("impresja.htm", "System IMPRESJA (dzień/noc)", "tkanina z pasów pełnych i transparentnych"),
           deep("rzymskie.htm", "Rolety rzymskie", "dekoracyjne fałdy tkaniny"),
           deep("dachowe.htm", "Rolety dachowe", "do okien połaciowych")])

pages["mini.htm"] = det_page("mini.htm",
    "Rolety system MINI - bezinwazyjny montaż na okno | ROLTAR Tarnów",
    "System MINI: rolety montowane bezinwazyjnie na skrzydłach okiennych. Mechanizmy t-4,2 i t-6, rura 17 mm, kompatybilność z MG II (do 400 cm).",
    "rolety.htm", "Rolety tekstylne", "System MINI",
    "Roletka na każdą szybę - montaż bez wiercenia w ramie okna.",
    "assets/rolety-wewnetrzne.jpg", "Rolety system MINI na skrzydle okna",
    "Bezinwazyjny montaż na skrzydłach",
    ["System MINI przeznaczony jest do rolet wolnowiszących, montowanych <strong>bezinwazyjnie na skrzydłach okiennych</strong>.",
     "Posiada dwa rodzaje mechanizmów hamujących: <strong>t-4,2 i t-6</strong>, dostosowanych do rury o średnicy 17 mm. To niezwykle prosty, praktyczny i niezawodny system, wzbogacony wieloma sposobami bezinwazyjnego montażu.",
     "Roletka montowana jest na specjalnych zaczepach do ramy okiennej - na każdą szybę oddzielnie. Do okien uchylnych stosuje się boczne prowadzenie na żyłkę lub magnesy przy listwie dolnej, aby przytrzymać materiał przy ramie podczas uchylania okna.",
     "Kompatybilność z systemem MG II daje możliwość wykonania rolet do <strong>400 cm szerokości</strong>."],
    feats=["Montaż bezinwazyjny na skrzydle okna",
           "Mechanizmy hamujące t-4,2 i t-6",
           "Rura o średnicy 17 mm",
           "Prowadzenie na żyłkę lub magnesy do okien uchylnych",
           "Kompatybilność z systemem MG II",
           "Rolety do 400 cm szerokości"],
    links_title="Zobacz również",
    links=[deep("wolnowiszace.htm", "Rolety wolnowiszące", "montaż do sufitu lub nadproża"),
           deep("besta.htm", "System BESTA", "kaseta na każdą szybę"),
           deep("luiza.htm", "System LUIZA", "kaseta z prowadnicami"),
           deep("impresja.htm", "System IMPRESJA (dzień/noc)", "wersja dzień-noc")])

pages["besta.htm"] = det_page("besta.htm",
    "Rolety w zabudowie BESTA - ROLTAR Tarnów",
    "System BESTA: rolety kasetowe montowane na każdą szybę, z napędem sprężynowym. Kolory oklein: złoty dąb, mahoń, orzech, biały, brąz.",
    "rolety.htm", "Rolety tekstylne", "System BESTA",
    "Elegancka kaseta montowana na szybę - parapet pozostaje w pełni wolny.",
    "assets/rolety-wewnetrzne.jpg", "Roleta kasetowa system BESTA",
    "Kaseta przy szybie, parapet wolny",
    ["Elegancki i praktyczny system roletkowy montowany <strong>na każdą szybę indywidualnie</strong>, dostępny z <strong>napędem sprężynowym</strong>.",
     "Posiada ładnie wyprofilowaną kasetkę osłonową oraz boczne prowadnice przytrzymujące materiał podczas uchylenia okna. Występuje w kilku kolorach popularnych oklein okiennych: <strong>złoty dąb, mahoń, orzech, biały, brąz</strong> i inne.",
     "Praktyczność systemu polega na tym, że materiał przesuwa się <strong>przy samej szybie</strong> - parapet pozostaje wolny, można na nim ustawić kwiaty, nie koliduje to z działaniem rolety."],
    feats=["Kaseta na każdą szybę osobno",
           "Napęd sprężynowy",
           "Prowadnice przytrzymujące materiał",
           "Kolory popularnych oklein okiennych",
           "Materiał przy szybie - wolny parapet",
           "Szybki i prosty montaż"],
    links_title="Zobacz również",
    links=[deep("wolnowiszace.htm", "Rolety wolnowiszące", "prosta roleta materiałowa"),
           deep("mini.htm", "System MINI", "montaż na skrzydła okienne"),
           deep("luiza.htm", "System LUIZA", "kaseta do ściany lub sufitu"),
           deep("impresja.htm", "System IMPRESJA (dzień/noc)", "tkanina naprzemienna")])

pages["luiza.htm"] = det_page("luiza.htm",
    "Rolety w zabudowie LUIZA - ROLTAR Tarnów",
    "System LUIZA: rolety tekstylne w zabudowie kasetowej z prowadnicami przestrzennymi. Sterowanie łańcuszkiem, sprężyną lub napędem elektrycznym.",
    "rolety.htm", "Rolety tekstylne", "System LUIZA",
    "Kaseta z prowadnicami przestrzennymi - do dużych okien i pełnego zaciemnienia.",
    "assets/rolety-wewnetrzne.jpg", "Roleta kasetowa system LUIZA",
    "Kaseta do ściany lub sufitu",
    ["System roletkowy w kasecie, mocowany do <strong>ściany lub sufitu</strong>, zasłaniający światło całego otworu okiennego.",
     "Posiada trzy sposoby podnoszenia i opuszczania: <strong>łańcuszek koralikowy, sprężynę lub napęd elektryczny</strong> (napęd polecany szczególnie do okien umieszczonych wysoko i trudno dostępnych).",
     "Przy użyciu odpowiednich tkanin daje możliwość <strong>całkowitego zaciemnienia</strong> pomieszczeń. Można tworzyć również wszelkiego rodzaju ekrany.",
     "Zaletą systemu LUIZA jest możliwość wykonania rolet o <strong>dużych gabarytach</strong>."],
    feats=["Montaż do ściany lub sufitu",
           "Sterowanie: łańcuszek, sprężyna, napęd elektryczny",
           "Możliwość pełnego zaciemnienia",
           "Możliwość tworzenia ekranów",
           "Rolety o dużych gabarytach",
           "Prowadnice przestrzenne"],
    links_title="Zobacz również",
    links=[deep("wolnowiszace.htm", "Rolety wolnowiszące", "bez kasety"),
           deep("besta.htm", "System BESTA", "kaseta na szybę"),
           deep("mini.htm", "System MINI", "montaż na skrzydła"),
           deep("impresja.htm", "System IMPRESJA (dzień/noc)", "tkanina naprzemienna"),
           deep("track.htm", "Panel track - japońska ściana", "duże przeszklenia")])

pages["rzymskie.htm"] = det_page("rzymskie.htm",
    "Rolety rzymskie - ROLTAR Tarnów",
    "Rolety rzymskie - dekoracyjne przesłony między roletą a zasłoną. Miękkie fałdy tkaniny, elegancki wygląd. Produkcja i montaż na wymiar.",
    "rolety.htm", "Rolety tekstylne", "Rolety rzymskie",
    "Efektowna osłona okienna, która jest jednocześnie ozdobą wnętrza.",
    "assets/rolety-wewnetrzne.jpg", "Roleta rzymska z miękkimi fałdami",
    "Pomiędzy roletą a zasłoną",
    ["Rolety rzymskie to przesłony pomiędzy <strong>klasyczną roletą a zasłoną</strong> - bardzo efektowny system osłony przeciwsłonecznej, służący w takim samym stopniu jako <strong>element dekoracyjny wnętrz</strong>.",
     "Tkanina podczas podnoszenia układa się w miękkie, dekoracyjne fałdy. Dostępna jest szeroka gama tkanin i kolorów, dzięki czemu roletę można idealnie dopasować do wystroju.",
     "Wykonujemy rolety rzymskie na wymiar - również do okien o nietypowych wymiarach."],
    feats=["Miękkie, dekoracyjne fałdy tkaniny",
           "Elegancki wygląd w każdym wnętrzu",
           "Duży wybór tkanin",
           "Sterowanie łańcuszkiem lub sznurkiem",
           "Wykonanie na wymiar",
           "Ochrona przed słońcem i wzrokiem sąsiadów"],
    links_title="Zobacz również",
    links=[deep("impresja.htm", "System IMPRESJA (dzień/noc)", "nowoczesna tkanina naprzemienna"),
           deep("wolnowiszace.htm", "Rolety wolnowiszące", "prosta roleta materiałowa"),
           deep("plisowane.htm", "Rolety plisowane", "składane tkaniny"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony")])

pages["dachowe.htm"] = det_page("dachowe.htm",
    "Rolety dachowe - rolety do okien połaciowych | ROLTAR Tarnów",
    "Rolety materiałowe do okien dachowych: wolnowiszące na ramie okna lub z osłoną wałka i prowadnicami. Kolory osłon: jasna sosna, ciemna sosna, biała, aluminiowa.",
    "rolety.htm", "Rolety tekstylne", "Rolety dachowe",
    "Osłony do okien połaciowych - w dwóch wersjach, dopasowanych do okna dachowego.",
    "assets/roleta-dachowa.jpg", "Roleta materiałowa na oknie dachowym",
    "Do okien połaciowych",
    ["Rolety materiałowe dachowe można wykonać w <strong>dwóch wersjach</strong>.",
     "<strong>Wersja pierwsza:</strong> rolety wolnowiszące na ramie okna, bez zabudowy wałka, z kilkoma punktami zatrzymania mocowanymi do ramy okiennej. Podnoszenie i opuszczanie odbywa się za pomocą <strong>sprężyny skrętnej</strong>.",
     "<strong>Wersja druga:</strong> rolety z osłoną wałka materiałowego oraz prowadnicami bocznymi, dające możliwość zatrzymania rolety w <strong>dowolnym miejscu okna</strong>.",
     "Kolory osłon: <strong>jasna sosna, ciemna sosna, biała, aluminiowa</strong>."],
    feats=["Dwie wersje: na ramę lub z osłoną wałka",
           "Podnoszenie sprężyną skrętną",
           "Prowadnice boczne w wersji kasetowej",
           "Zatrzymanie rolety w dowolnym miejscu okna",
           "Kolory: jasna sosna, ciemna sosna, biała, aluminiowa",
           "Montaż na wymiar"],
    links_title="Zobacz również",
    links=[deep("impresja.htm", "System IMPRESJA (dzień/noc)", "tkanina naprzemienna"),
           deep("wolnowiszace.htm", "Rolety wolnowiszące", "montaż do sufitu lub nadproża"),
           deep("plisowane.htm", "Rolety plisowane", "składane tkaniny"),
           deep("moskitiery.htm", "Moskitiery", "siatki również na okna dachowe")])

pages["impresja.htm"] = det_page("impresja.htm",
    "Rolety dzień-noc IMPRESJA - ROLTAR Tarnów",
    "Rolety tekstylne IMPRESJA (dzień/noc) z tkaniny z poziomych pasów pełnych i transparentnych. Systemy: kaseta, mini, maxi - do 2,5 m wysokości.",
    "rolety.htm", "Rolety tekstylne", "System IMPRESJA - dzień/noc",
    "Nowoczesna roleta z tkaniny naprzemiennej: pełne i transparentne pasy dają efekt żaluzji.",
    "assets/rolety-wewnetrzne.jpg", "Roleta dzień-noc w oknie",
    "Tkanina, która działa jak żaluzja",
    ["Rolety tekstylne spotykane pod nazwami „impresja” lub „dzień/noc” to jeden z nowszych systemów rolet tekstylnych, polegający na zastosowaniu materiału wykonanego z poziomych pasów - <strong>pełnych i transparentnych</strong>.",
     "Dzięki podwójnemu nawinięciu materiału uzyskuje się efekt przypominający działanie żaluzji poziomych. Poprzez odpowiednie ustawienie wysokości tkaniny można płynnie regulować zasłonięcie wnętrza.",
     "Atrakcyjna kolekcja tkanin oraz dopasowana kolorystyka detali pozwala optymalnie dobrać roletę do wystroju wnętrza."],
    feats=["Tkanina z pasów pełnych i transparentnych",
           "Efekt żaluzji - płynna regulacja światła",
           "Wersje: kaseta (do 1,25 m), mini (do 1,5 m), maxi (do 2,5 m)",
           "Montaż na ramie okiennej w systemie mini",
           "Duży wybór tkanin i kolorów",
           "Ochrona przed wzrokiem sąsiadów"],
    links_title="Zobacz również",
    links=[deep("wolnowiszace.htm", "Rolety wolnowiszące", "klasyczna roleta materiałowa"),
           deep("besta.htm", "System BESTA", "kaseta na szybę"),
           deep("luiza.htm", "System LUIZA", "kaseta z prowadnicami"),
           deep("mini.htm", "System MINI", "montaż na skrzydła okienne"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony")])

pages["track.htm"] = det_page("track.htm",
    "Panel track - japońska ściana | ROLTAR Tarnów",
    "Żaluzje panelowe (japońska ściana, panel track): panele 40-110 cm na wielotorowej szynie 2-5 torów. Sterowanie ręczne, sznurkowe lub elektryczne G-rail.",
    "rolety.htm", "Rolety tekstylne", "Panel track - japońska ściana",
    "Szerokie, przesuwne panele - nowoczesna alternatywa dla żaluzji pionowych.",
    "assets/zaluzje-pionowe.jpg", "Panele tekstylne przy dużym oknie",
    "Nowoczesne przesłony do dużych okien",
    ["Żaluzje panelowe, zwane inaczej storami japońskimi (z angielskiego <strong>panel track</strong>), są ciekawą alternatywą dla verticali - podobnie jak one mogą zakrywać <strong>duże połacie okien</strong>.",
     "Panele mają szerokość od <strong>40 do 110 cm</strong> i poruszają się po wielotorowej szynie (od 2 do 5 torów). Żaluzje panelowe nadają wnętrzom bardzo nowoczesny wygląd, nawiązując jednocześnie do tradycji ruchomych ścian japońskich.",
     "Obok tradycyjnych paneli z tkanin dużą popularnością cieszą się panele z tkaniny typu <strong>woven paper</strong> oraz w formie sznurków, tzw. <strong>strings</strong>."],
    feats=["Panele o szerokości 40-110 cm",
           "Szyna wielotorowa (2-5 torów)",
           "Tkaniny, woven paper, strings",
           "Sterowanie ręczne (rączka) lub sznurkowe",
           "Sterowanie elektryczne G-rail",
           "Nawet 5 zaprogramowanych położeń paneli"],
    links_title="Zobacz również",
    links=[deep("pionowe.htm", "Żaluzje pionowe VERTICALE", "klasyczne piony do dużych okien"),
           deep("impresja.htm", "System IMPRESJA (dzień/noc)", "rolety z tkaniny naprzemiennej"),
           deep("luiza.htm", "System LUIZA", "kaseta z prowadnicami"),
           deep("rolety.htm", "Rolety i żaluzje", "wszystkie osłony")])

# ======================================================================
# BRAMY
# ======================================================================

pages["bs.htm"] = det_page("bs.htm",
    "Bramy segmentowe - ROLTAR Tarnów",
    "Bramy garażowe segmentowe: segmenty wjeżdżające pod dach garażu. Wersje ze stali i z wykończeniem drewnopodobnym, z drzwiami bocznymi.",
    "bramy.htm", "Bramy", "Bramy segmentowe",
    "Klasyka garażu: brama podnoszona do góry, segmenty chowają się pod sufitem.",
    "assets/bramy.jpg", "Segmentowa brama garażowa",
    "Segmenty wjeżdżają pod dach",
    ["Brama segmentowa składa się z kilku segmentów, które przy otwieraniu <strong>wjeżdżają pod dach garażu</strong>, prowadzone po szynach - nie zajmują miejsca przed garażem.",
     "W zależności od domu i upodobań proponujemy wersje z panelami stalowymi (<strong>elegancja ze stali</strong>) oraz z wykończeniem w naturalnym <strong>uroku drewna</strong> - w obu wariantach możliwe są również drzwi boczne.",
     "Bramy segmentowe można wyposażyć w napęd elektryczny z pilotem i automatykę."],
    feats=["Segmenty wjeżdżające pod dach",
           "Wersja stalowa i z wykończeniem drewnopodobnym",
           "Możliwość wykonania drzwi bocznych",
           "Cicha praca z napędem",
           "Dobre ocieplenie paneli",
           "Sterowanie pilotem"],
    links_title="Zobacz również",
    links=[deep("brrol.htm", "Bramy rolowane", "pancerz zwijany w kasetę"),
           deep("bpsp.htm", "Bramy wjazdowe przesuwne", "samonośne, do ogrodzeń"),
           deep("bp.htm", "Bramy przemysłowe", "segmentowe ocieplane"),
           deep("ndbr.htm", "Napędy do bram", "automatyka i akcesoria"),
           deep("bramy.htm", "Bramy - oferta", "wszystkie rodzaje bram")])

pages["brrol.htm"] = det_page("brrol.htm",
    "Bramy rolowane - system Aluprof PA 77 | ROLTAR Tarnów",
    "Bramy garażowe rolowane z pancerzem z profili PA 77: funkcjonalne, bezpieczne, estetyczne. Z napędem, fotokomórką i awaryjnym napędem ręcznym.",
    "bramy.htm", "Bramy", "Bramy rolowane",
    "Pancerz zwijany w kasetę nad otworem - oszczędność miejsca i pełna wygoda.",
    "assets/brama-rolowana.jpg", "Brama rolowana z kasetą nad wjazdem",
    "Zwijana w kasetę",
    ["Rolowane bramy garażowe to rozwiązanie wszechstronne - bramę można zamontować zarówno w budowanych obiektach, jak i w już istniejących. Ważną zaletą jest <strong>oszczędność miejsca</strong>: pracująca w płaszczyźnie pionowej brama sprawdza się tam, gdzie podjazd jest krótki lub prowadzi wprost na ulicę - podniesiony pancerz nie ogranicza widoczności.",
     "Pancerz wykonany z profili <strong>PA 77</strong> z wysokogatunkowych blach aluminiowych jest odporny na działania mechaniczne i czynniki atmosferyczne. W zależności od potrzeb profile PA 77 można łączyć z profilami <strong>z przeszkleniem PER 77</strong> i <strong>wentylacyjnymi PEW 77</strong>.",
     "Brama standardowo wyposażona jest w zabezpieczenie przed podniesieniem, a fotokomórka zatrzymuje bramę, gdy w polu jej działania znajdzie się przeszkoda. W razie zaniku napięcia bramę otworzy się <strong>awaryjnym napędem ręcznym (ANR)</strong>.",
     "Zastosowanie napędu elektrycznego i sterowania radiowego zapewnia pełny komfort - bramą steruje się pilotem bez wysiadania z samochodu."],
    feats=["Pancerz z profili PA 77 (Aluprof)",
           "Profile z przeszkleniem PER 77 i wentylacyjne PEW 77",
           "Oszczędność miejsca - zwijanie w kasetę",
           "Zabezpieczenie przed podniesieniem",
           "Fotokomórka bezpieczeństwa",
           "Awaryjny napęd ręczny (ANR)",
           "Sterowanie radiowe pilotem"],
    links_title="Zobacz również",
    links=[deep("bs.htm", "Bramy segmentowe", "panele wjeżdżające pod dach"),
           deep("bpsp.htm", "Bramy wjazdowe przesuwne", "samonośne"),
           deep("ndbr.htm", "Napędy do bram", "automatyka"),
           deep("bramy.htm", "Bramy - oferta", "wszystkie rodzaje bram")])

pages["bpsp.htm"] = det_page("bpsp.htm",
    "Bramy wjazdowe przesuwne samonośne - ROLTAR Tarnów",
    "Bramy wjazdowe przesuwne samonośne z zabezpieczeniami antykorozyjnymi. Dopasowanie do ogrodzeń panelowych, możliwość automatyki.",
    "bramy.htm", "Bramy", "Bramy wjazdowe przesuwne samonośne",
    "Funkcjonalne zamknięcie posesji - brama przesuwa się wzdłuż ogrodzenia.",
    "assets/brama-przesuwna.jpg", "Przesuwna brama wjazdowa",
    "Samonośna brama przesuwna",
    ["Bramy wjazdowe wykonane są z <strong>najwyższej jakości materiałów</strong>, z wykorzystaniem zabezpieczeń antykorozyjnych stosowanych w procesie produkcji.",
     "Zaletą bram wjazdowych jest możliwość dopasowania ich do <strong>ogrodzeń panelowych</strong>, tak by ogrodzenie wraz z bramą stanowiły estetyczne zamknięcie działki.",
     "Do bramy wjazdowej przesuwnej samonośnej można zastosować <strong>automatykę z wieloma opcjami</strong>, co pozwala na łatwe i bardziej komfortowe użytkowanie bramy."],
    feats=["Materiały najwyższej jakości",
           "Zabezpieczenia antykorozyjne",
           "Dopasowanie do ogrodzeń panelowych",
           "Automatyka z wieloma opcjami",
           "Sterowanie radiowe",
           "Estetyczne zamknięcie posesji"],
    links_title="Zobacz również",
    links=[deep("bs.htm", "Bramy segmentowe", "do garaży"),
           deep("bp.htm", "Bramy przemysłowe", "do hal i zakładów"),
           deep("ndbr.htm", "Napędy do bram", "siłowniki do bram przesuwnych"),
           deep("bramy.htm", "Bramy - oferta", "wszystkie rodzaje bram")])

pages["bp.htm"] = det_page("bp.htm",
    "Bramy przemysłowe segmentowe - ROLTAR Tarnów",
    "Bramy przemysłowe segmentowe, stalowe ocieplane, do hal i zakładów. Napęd ręczny łańcuchowy lub elektryczny z systemami zabezpieczeń.",
    "bramy.htm", "Bramy", "Bramy przemysłowe",
    "Solidne bramy do hal, magazynów i zakładów produkcyjnych.",
    "assets/brama-przemyslowa.jpg", "Przemysłowa brama segmentowa hali",
    "Dla przemysłu i usług",
    ["Oferujemy <strong>stalowe, ocieplane bramy segmentowe</strong>, przeznaczone do obiektów przemysłowych, hal magazynowych i usługowych.",
     "Przy napędach bram mają Państwo do wyboru: <strong>system ręczny (łańcuchowy)</strong> lub <strong>elektryczny z różnymi systemami zabezpieczeń</strong>.",
     "Dobieramy bramę do wielkości otworu, częstotliwości użytkowania i wymagań dotyczących izolacji."],
    feats=["Stalowa, ocieplana konstrukcja",
           "Napęd ręczny (łańcuchowy)",
           "Napęd elektryczny z zabezpieczeniami",
           "Do hal, magazynów i zakładów",
           "Wykonanie na wymiar",
           "Montaż i serwis"],
    links_title="Zobacz również",
    links=[deep("bs.htm", "Bramy segmentowe", "wersja garażowa"),
           deep("bpsp.htm", "Bramy wjazdowe przesuwne", "samonośne"),
           deep("szlabany.htm", "Szlabany i zapory", "oraz napędy do bram przemysłowych"),
           deep("ndbr.htm", "Napędy do bram", "automatyka"),
           deep("bramy.htm", "Bramy - oferta", "wszystkie rodzaje bram")])

# ======================================================================
# NAPĘDY I AUTOMATYKA
# ======================================================================

pages["ndr.htm"] = det_page("ndr.htm",
    "Silniki i sterowania do rolet okiennych - ROLTAR Tarnów",
    "Napędy i sterowania do rolet: siłownik rurowy o cichej pracy, sterowanie centralne, przełączniki programowe i inteligentne. Montaż w istniejących roletach.",
    "napedy.htm", "Napędy i automatyka", "Silniki i sterowania do rolet",
    "Rolety obsługiwane „jednym palcem” - a jeśli zapomnisz je opuścić lub podnieść o odpowiedniej porze, zrobią to za Ciebie.",
    "assets/napedy.jpg", "Silnik rurowy i sterownik do rolety",
    "Automatyka do rolet okiennych",
    ["<strong>Siłownik rurowy</strong> - wyjątkowo cicha praca. Można go zamontować w roletach <strong>już istniejących</strong>, bez wymiany rolety.",
     "<strong>Sterowanie centralne</strong> - umożliwia sterowanie pojedynczą roletą lub grupą rolet.",
     "<strong>Przełącznik programowy</strong> - otwiera i zamyka rolety o zaprogramowanych porach; w czasie wyjazdu domowników stwarza wrażenie ich obecności.",
     "<strong>Przełącznik inteligentny</strong> z 24-godzinną pamięcią - po zaprogramowaniu zapamiętuje godzinę wysłania polecenia otwarcia lub zamknięcia rolety i powtarza je w cyklu dobowym.",
     "Czujnik słońca lub przełącznik programowy zadbają o to, by przy każdej pogodzie zapewnić pomieszczeniu najlepszą osłonę."],
    feats=["Siłownik rurowy - cicha praca",
           "Montaż w istniejących roletach",
           "Sterowanie centralne (rolka lub grupa)",
           "Przełącznik programowy - symulacja obecności",
           "Przełącznik inteligentny z pamięcią 24 h",
           "Czujnik słońca"],
    links_title="Zobacz również",
    links=[deep("ndbr.htm", "Napędy do bram", "automatyka bram wjazdowych i garażowych"),
           deep("ndm.htm", "Napędy do markiz", "silniki i automatyka słoneczno-wiatrowa"),
           deep("napedy.htm", "Napędy i automatyka", "pełna oferta"),
           deep("rolety.htm", "Rolety i żaluzje", "rolety z napędem")])

pages["ndbr.htm"] = det_page("ndbr.htm",
    "Napędy i automatyka do bram - ROLTAR Tarnów",
    "Napędy do bram garażowych, skrzydłowych, przesuwnych i podziemne siłowniki. Sterowanie radiowe, fotokomórki, klawiatury kodowe. Marki: Marantec, Nice, FAAC, Came.",
    "napedy.htm", "Napędy i automatyka", "Napędy i automatyka do bram",
    "Niezawodne otwieranie i zamykanie bramy bez względu na warunki pogodowe.",
    "assets/bramy.jpg", "Brama garażowa z napędem",
    "Automatyka do bram",
    ["Napędy do bram garażowych gwarantują <strong>niezawodne otwieranie i zamykanie bramy</strong> bez względu na warunki pogodowe. Montujemy napędy do bram <strong>skrzydłowych, przesuwnych i garażowych</strong>.",
     "Sterowanie: <strong>radiowe (pilot)</strong>, przyciski ścienne, klawiatura kodowa, wyłączniki kluczykowe. Bramka świetlna (fotokomórka) podnosi bezpieczeństwo użytkowania.",
     "Napędy cechują bardzo płynne ruchy, stabilne bezpieczeństwo, <strong>ABS w układzie napędowym</strong> i zoptymalizowane zużycie prądu. Oferujemy również <strong>wciągarki do bram uchylnych i segmentowych</strong> - tym samym pilotem można otwierać bramę wjazdową i garażową.",
     "W ofercie także <strong>elektromechaniczne siłowniki do bram przesuwnych</strong> (trwała obudowa z mechanizmem odblokowania, zabezpieczenie elektroniki przed czynnikami atmosferycznymi, przekładnia ze stopu brązu zapewniająca cichą i długotrwałą pracę) oraz <strong>siłowniki do bram skrzydłowych</strong> - naziemne i <strong>podziemne</strong>, z układami awaryjnego odblokowania."],
    feats=["Napędy do bram garażowych, skrzydłowych i przesuwnych",
           "Sterowanie radiowe pilotem",
           "Bramka świetlna (fotokomórka)",
           "Klawiatury kodowe i wyłączniki kluczykowe",
           "Siłowniki naziemne i podziemne",
           "Wciągarki do bram uchylnych i segmentowych",
           "Systemy awaryjnego odblokowania"],
    links_title="Zobacz również",
    links=[deep("ndr.htm", "Silniki do rolet okiennych", "napędy i sterowania"),
           deep("ndm.htm", "Napędy do markiz", "silniki i automatyka"),
           deep("szlabany.htm", "Szlabany i zapory drogowe", "wjazdy i parkingi"),
           deep("napedy.htm", "Napędy i automatyka", "pełna oferta"),
           deep("bramy.htm", "Bramy - oferta", "bramy z napędem")])

pages["ndm.htm"] = det_page("ndm.htm",
    "Napędy do markiz - ROLTAR Tarnów",
    "Napędy do markiz i ogrodów zimowych: napęd rurowy o cichej pracy, radiowa automatyka słoneczno-wiatrowa i wiatrowa. Sterowanie pilotem.",
    "napedy.htm", "Napędy i automatyka", "Napędy do markiz",
    "Markiza zamknie się bez wysiłku - przyciskiem lub w pełni automatycznie.",
    "assets/markiza.jpg", "Markiza tarasowa z napędem",
    "Automatyka do markiz i ogrodów zimowych",
    ["<strong>Napęd rurowy</strong> - wyjątkowo cicha praca. Można go zamontować w markizach <strong>już istniejących</strong>.",
     "<strong>Radiowa automatyka słoneczno-wiatrowa</strong> - markiza rozwija się i zwija automatycznie w zależności od siły wiatru lub intensywności nasłonecznienia. Można nią sterować również pilotem.",
     "<strong>Radiowa automatyka wiatrowa</strong> - w momencie zerwania się silnego wiatru wysunięta markiza zostanie automatycznie zwinięta, co chroni tkaninę i konstrukcję."],
    feats=["Napęd rurowy - cicha praca",
           "Montaż w istniejących markizach",
           "Automatyka słoneczno-wiatrowa",
           "Automatyka wiatrowa - ochrona przed wichurą",
           "Sterowanie pilotem",
           "Do markiz i ogrodów zimowych"],
    links_title="Zobacz również",
    links=[deep("ndbr.htm", "Napędy do bram", "automatyka bram"),
           deep("ndr.htm", "Silniki do rolet okiennych", "napędy i sterowania"),
           deep("napedy.htm", "Napędy i automatyka", "pełna oferta"),
           deep("markizy.htm", "Markizy", "tarasowe, balkonowe, koszowe")])

pages["szlabany.htm"] = det_page("szlabany.htm",
    "Szlabany i zapory drogowe - ROLTAR Tarnów",
    "Szlabany i zapory drogowe do wjazdów i parkingów: różnorodne warianty montażowe. Oraz napędy do bram przemysłowych - przesuwnych i segmentowych.",
    "napedy.htm", "Napędy i automatyka", "Szlabany i zapory drogowe",
    "Kontrolowany wjazd na posesję, parking lub teren firmy.",
    "assets/szlaban.jpg", "Automatyczny szlaban przy wjeździe",
    "Kontrola wjazdu",
    ["Oferujemy <strong>szlabany i zapory drogowe</strong> w różnorodnych wariantach montażowych - optymalne rozwiązanie w każdej sytuacji i bezpieczne w użytkowaniu.",
     "Montujemy również <strong>napędy do bram przemysłowych</strong>: napęd boczny do bramy przesuwnej przemysłowej oraz napęd do bramy segmentowej przemysłowej.",
     "Dobieramy długość ramienia szlabanu i system sterowania (pilot, przycisk, czytnik) do indywidualnych potrzeb."],
    feats=["Szlabany i zapory drogowe",
           "Różnorodne warianty montażowe",
           "Napęd boczny do bram przesuwnych przemysłowych",
           "Napęd do bram segmentowych przemysłowych",
           "Sterowanie pilotem lub przyciskiem",
           "Bezpieczne w użytkowaniu"],
    links_title="Zobacz również",
    links=[deep("ndbr.htm", "Napędy do bram", "automatyka bram wjazdowych i garażowych"),
           deep("bp.htm", "Bramy przemysłowe", "segmentowe ocieplane"),
           deep("napedy.htm", "Napędy i automatyka", "pełna oferta")])

# ======================================================================
# MARKIZY
# ======================================================================

pages["mtaras.htm"] = det_page("mtaras.htm",
    "Markizy tarasowe - ROLTAR Tarnów",
    "Markizy tarasowe: Malta, Silver Plus, Australia, Jamaica, Palladio i Dakar. Moduły do 16 m szerokości, napęd korbowy lub elektryczny.",
    "markizy.htm", "Markizy", "Markizy tarasowe",
    "Zacienienie dużych tarasów, ogrodów zimowych i stref wypoczynku.",
    "assets/markiza.jpg", "Markiza tarasowa nad tarasem",
    "Cień na dużym tarasie",
    ["Eleganckie i praktyczne markizy pomogą ukryć się przed palącymi promieniami słońca w upalne dni. <strong>Istnieje możliwość łączenia markiz w moduły o szerokości do 16 m</strong>.",
     "Napęd każdej markizy może być ręczny (korba) lub elektryczny - bogaty program automatyki pozwala zaspokoić wszelkie gusta. Markizę można pochylać pod dowolnym kątem, a dzięki estetyce są one doskonałym elementem upiększającym taras."],
    model_extra=models_section("Modele markiz tarasowych",
        "Wszystkie modele wykonujemy na wymiar, w wybranych kolorach tkanin i konstrukcji.",
        [("Malta", "", "Lekka, wolnowisząca markiza, doskonała do przesłonięcia niewielkiego tarasu lub balkonu. Kompaktowa konstrukcja z uniwersalnym uchwytem ścienno-sufitowym, który umożliwia pochylenie markizy nawet do 85 stopni. Konstrukcja lakierowana proszkowo na pięć standardowych kolorów."),
         ("Silver Plus", "", "Markiza o lekkiej konstrukcji - ekonomiczne rozwiązanie do zacieniania tarasów i balkonów średniej wielkości. Rozkładane ramiona ze stopu aluminium, solidna stalowa belka kwadratowa, opcjonalny aluminiowy daszek ochraniający zwiniętą tkaninę. Konstrukcja w kolorze białym."),
         ("Australia", "", "Markiza do dużych tarasów i instalacji komercyjnych. Ramiona na aluminiowych uchwytach z odlewu ciśnieniowego, centralna podpora rury nawojowej zapewnia dobrze napiętą tkaninę na dużej szerokości. Kolory: biały, beżowy, brązowy i srebrny z wykończeniem grafitowym."),
         ("Jamaica", "", "Połączenie elegancji i wytrzymałości - idealna do dużych tarasów i miejsc intensywnie użytkowanych. Dzięki centralnej podporze rury nawojowej tkanina jest zawsze równomiernie napięta. Kolory: biały, beżowy, brązowy lub srebrny; opcjonalny daszek aluminiowy."),
         ("Palladio", "", "Elegancka markiza z kasetą - ramiona podnoszą się do góry, a kaseta domyka się szczelnie, osłaniając zwiniętą tkaninę. Podpory sprężyste rury nawojowej napinają tkaninę równomiernie. Kolory: biały, beżowy, brązowy lub srebrny."),
         ("Dakar", "", "Markiza kasetowa do zacieniania większych tarasów. Pełna kaseta o opływowych kształtach osłania tkaninę i ramiona przed czynnikami atmosferycznymi, a uszczelki zabezpieczające chronią tkaninę w środku. Kolory: biały, srebrny z wykończeniem grafitowym, beżowy lub brązowy.")]),
    links_title="Zobacz również",
    links=[deep("mbalkon.htm", "Markizy balkonowe ITALIA", "nadokienno-balkonowe"),
           deep("mkosz.htm", "Markizy koszowe", "z reklamą lokalu"),
           deep("mniest.htm", "Markizy niestandardowe", "zadaszenia, pergole, ogrody zimowe"),
           deep("markizy2.htm", "Markizy - przegląd modeli", "wszystkie modele"),
           deep("markizy.htm", "Markizy - oferta", "główna strona markiz")])

pages["mbalkon.htm"] = det_page("mbalkon.htm",
    "Markizy balkonowe ITALIA - ROLTAR Tarnów",
    "Markizy balkonowe ITALIA: nadokienno-balkonowa, w kasecie i poręczowa. Lekka konstrukcja, sprężyna napinająca tkaninę, kolor biały.",
    "markizy.htm", "Markizy", "Markizy balkonowe",
    "Osłona balkonów, tarasów, werand i witryn - lekka konstrukcja, łatwy montaż.",
    "assets/markiza-balkonowa.jpg", "Markiza balkonowa nad balustradą",
    "Wersje ITALIA",
    ["Markizy balkonowe ITALIA przeznaczone są do zacieniania i osłony <strong>wnęk okiennych, witryn, balkonów, tarasów i werand</strong>.",
     "Opuszczane ramiona z aluminium wyposażono w sprężynę, która napina tkaninę i <strong>zapobiega składaniu ramion pod naporem wiatru</strong>. Ciężar markizy rozłożony jest na uchwyty ramion i rurę nawojową, dlatego ITALIA może być mocowana nawet tam, gdzie wytrzymałość podłoża nie pozwala na markizę tarasową ze składanymi ramionami."],
    model_extra=models_section("Warianty modelu ITALIA",
        "Lekka konstrukcja markiz balkonowych sprawia, że montaż jest bardzo łatwy.",
        [("ITALIA", "", "Markiza nadokienno-balkonowa do wnęk okiennych, witryn, balkonów, tarasów i werand. Sprężyna w opuszczanych ramionach napina tkaninę i chroni przed wiatrem. Konstrukcja w kolorze białym."),
         ("ITALIA w kasecie", "", "Wersja z aluminiową kasetą osłaniającą tkaninę przed niekorzystnymi warunkami atmosferycznymi. Taka sama lekka konstrukcja i łatwy montaż jak w podstawowej ITALII. Kolor biały."),
         ("ITALIA poręczowa", "", "Estetyczna osłona balkonów, tarasów i wnęk balkonowych - ramiona mocowane do balustrady pozwalają ustawić odpowiedni kąt pochylenia, a belkę przednią z materiałem zaczepia się na hakach. Konstrukcja w kolorze białym.")]),
    links_title="Zobacz również",
    links=[deep("mtaras.htm", "Markizy tarasowe", "modele Malta, Silver Plus, Australia i inne"),
           deep("mkosz.htm", "Markizy koszowe", "z reklamą lokalu"),
           deep("mniest.htm", "Markizy niestandardowe", "zadaszenia, pergole, ogrody zimowe"),
           deep("markizy.htm", "Markizy - oferta", "główna strona markiz")])

pages["mkosz.htm"] = det_page("mkosz.htm",
    "Markizy koszowe - ROLTAR Tarnów",
    "Markizy koszowe z konstrukcji aluminiowej pokryte folią termokurczliwą, zbrojoną lub dralonem. Idealne pod reklamy i nazwy lokali.",
    "markizy.htm", "Markizy", "Markizy koszowe",
    "Charakterystyczne markizy hoteli, restauracji i pubów - z miejscem na reklamę.",
    "assets/markiza-koszowa.jpg", "Markiza koszowa nad witryną lokalu",
    "Wizytówka lokalu",
    ["Markizy koszowe stanowią element charakterystyczny dla <strong>hoteli, restauracji i pubów</strong> - zaznaczają strefę wejściową lokali i nadają im charakter.",
     "Wykonane z <strong>konstrukcji aluminiowej</strong>, pokryte folią termokurczliwą lub zbrojoną, a także dralonem. Są doskonałym miejscem na umieszczenie <strong>reklamy, nazwy kawiarni, cukierni</strong> itp.",
     "Chronią przed słońcem i deszczem, a jednocześnie pięknie eksponują szyld lokalu."],
    feats=["Konstrukcja aluminiowa",
           "Folia termokurczliwa, zbrojona lub dralon",
           "Miejsce na reklamę i nazwę lokalu",
           "Ochrona przed słońcem i deszczem",
           "Do hoteli, restauracji i pubów",
           "Wykonanie na wymiar"],
    links_title="Zobacz również",
    links=[deep("mtaras.htm", "Markizy tarasowe", "modele Malta, Silver Plus, Australia i inne"),
           deep("mbalkon.htm", "Markizy balkonowe ITALIA", "nadokienno-balkonowe"),
           deep("mniest.htm", "Markizy niestandardowe", "zadaszenia, pergole, ogrody zimowe"),
           deep("markizy.htm", "Markizy - oferta", "wszystkie markizy")])

pages["mniest.htm"] = det_page("mniest.htm",
    "Markizy niestandardowe, zadaszenia i pergole - ROLTAR Tarnów",
    "Zadaszenia nietypowe, konstrukcje zadaszeń dużych powierzchni, pergole i systemy do ogrodów zimowych. Wykonanie na wymiar.",
    "markizy.htm", "Markizy", "Zadaszenia nietypowe i pergole",
    "Rozwiązania szyte na miarę: zadaszenia, pergole, ogrody zimowe.",
    "assets/pergola.jpg", "Pergola z rozsuwanym zadaszeniem nad tarasem",
    "Na wymiar i na specjalne życzenie",
    ["Poza standardowymi markizami wykonujemy <strong>zadaszenia nietypowe</strong> oraz <strong>konstrukcje zadaszeń dużych powierzchni</strong>.",
     "W ofercie znajdują się <strong>pergole</strong> - wolnostojące lub przyścienne konstrukcje z rozsuwanym zadaszeniem, idealne do stref wypoczynku w ogrodzie i przy domu.",
     "Projektujemy również <strong>systemy do ogrodów zimowych</strong> - osłony przeciwsłoneczne dopasowane do przeszkleń dachowych i pionowych."],
    feats=["Zadaszenia nietypowych kształtów",
           "Konstrukcje dużych powierzchni",
           "Pergole wolnostojące i przyścienne",
           "Systemy do ogrodów zimowych",
           "Wykonanie na wymiar",
           "Doradztwo i montaż"],
    links_title="Zobacz również",
    links=[deep("mtaras.htm", "Markizy tarasowe", "modele tarasowe"),
           deep("mbalkon.htm", "Markizy balkonowe ITALIA", "nadokienno-balkonowe"),
           deep("mkosz.htm", "Markizy koszowe", "z reklamą lokalu"),
           deep("markizy.htm", "Markizy - oferta", "wszystkie markizy")])

pages["markizy2.htm"] = det_page("markizy2.htm",
    "Markizy - modele i rodzaje | ROLTAR Tarnów",
    "Modele markiz: tarasowe Malta, Silver Plus, Australia, Jamaica, Palladio, Dakar; balkonowe ITALIA; koszowe i niestandardowe. Produkcja na wymiar.",
    "markizy.htm", "Markizy", "Markizy - przegląd modeli",
    "Kompletna oferta markiz: od lekkich balkonowych po moduły tarasowe o szerokości do 16 metrów.",
    "assets/markiza.jpg", "Rozłożona markiza nad tarasem",
    "Wybierz markizę dla siebie",
    ["Markizy to eleganckie i praktyczne osłony, które nie są konstrukcją stałą - można je <strong>rozwijać i zwijać</strong> w zależności od potrzeby. Wykonane są z materiałów nieprzemakalnych, a konstrukcja z profili aluminiowych lakierowanych proszkowo gwarantuje długoletnie użytkowanie.",
     "Rozwijanie i zwijanie może odbywać się za pomocą <strong>przekładni korbowej lub silnika elektrycznego</strong>. Bardzo duży wybór materiałów pozwala dopasować markizę do elewacji budynku."],
    model_extra=models_section("Dostępne modele",
        "Każdy rodzaj znajdziesz na osobnej stronie z opisem i szczegółami.",
        [("Markizy tarasowe", "szczegóły na podstronie", "Lekka Malta przez ekonomiczną Silver Plus, przez duże Australia i Jamaica, po kasetowe Palladio i Dakar. Możliwość łączenia w moduły do 16 m szerokości."),
         ("Markizy balkonowe", "szczegóły na podstronie", "Wersje ITALIA, ITALIA w kasecie i ITALIA poręczowa - lekkie konstrukcje do balkonów, wnęk okiennych i werand."),
         ("Markizy koszowe", "szczegóły na podstronie", "Aluminiowa konstrukcja pokryta folią lub dralonem - doskonałe miejsce na reklamę i nazwę lokalu."),
         ("Zadaszenia i pergole", "szczegóły na podstronie", "Rozwiązania niestandardowe: zadaszenia dużych powierzchni, pergole i systemy do ogrodów zimowych.")]),
    links_title="Zobacz również",
    links=[deep("mtaras.htm", "Markizy tarasowe", "modele i szczegóły"),
           deep("mbalkon.htm", "Markizy balkonowe ITALIA", "nadokienno-balkonowe"),
           deep("mkosz.htm", "Markizy koszowe", "z reklamą lokalu"),
           deep("mniest.htm", "Markizy niestandardowe", "zadaszenia i pergole"),
           deep("markizy.htm", "Markizy - oferta", "główna strona markiz")])
